### PR TITLE
Add ability to have units specified for numeric

### PR DESCRIPTION
**Pull request by gorj-tessella**
When there is only one unit or a default unit specifed, show the unit
to the right of the field. Units now render to the right of the field,
not on top of it.

Also make a number of changes in CSS for simplicity, responsiveness. 

This partially addresses #15. Several of the changes rely on flexbox layout, which is not available in older browsers but dramatically simplifies some layouts.

### CODE REVIEW

**Comment by gorj-tessella** [comment]
Moved assets into assets.js.erb. This allows me to use index.html and index2.html for testing and development.

**Comment by gorj-tessella** [comment]
Please check that the css changes work properly on firefox or all other browsers. They definitely work on chrome.

**Comment by bwlang** [comment]
one issue:

image

the polymerase selection box breaks out of the box (see image) on firefox and opera.

**Comment by gorj-tessella** [comment]
I suspect this is due to conflicts between the new css in plate-map and some css in ebase; Victor and I will resolve this with the changes on the ebase feature/plate-map-UI branch. 

In the meantime you can try deleting all of the style elements (which we put in place to override earlier plate-map css) in ebase/app/views/well_set_wells/visual_edit.html.erb. That should make a difference.

**Comment by bwlang** [comment]
it's not a big problem - but if we can easily fix it, that would be nice.  might just be a configuration to get it to wrap?
i noticed some other boxes just now do not show anything when the input is too long...
e.g.
https://ebase-c.neb.com/well_sets/24209/wells/visual_edit buffer looks blank, but really has this long name: 	4387P ws Luna Universal 1-Step Reaction Mix (M3005) lot 0011607 mm

**Comment by gorj-tessella** [comment]
@bwlang I think we should merge this and #20 so we can make necessary changes in ebase, then verify that everything looks correct to you and if not create a new issue.

**Pull request merged**
